services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - auth_db
      - tasks_db
      - stats_db


  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    env_file:
      - auth_service/.env
    depends_on:
      - auth_db
      - redis

  tasks_service:
    build: ./tasks_service
    ports:
      - "8001:8001"
    env_file:
      - tasks_service/.env
    depends_on:
      - tasks_db

  stats_service:
    build: ./stats_service
    ports:
      - "8002:8002"
    env_file:
      - stats_service/.env
    depends_on:
      - stats_db
      - redis

  auth_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=auth_db
    volumes:
      - auth_data:/var/lib/postgresql/data

  tasks_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tasks_db
    volumes:
      - tasks_data:/var/lib/postgresql/data

  stats_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=stats_db
    volumes:
      - stats_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  auth_service_worker:
    build: ./auth_service
    command: celery -A auth_service worker --loglevel=info
    env_file:
      - auth_service/.env
    depends_on:
      - redis
      - auth_db

  stats_service_worker:
    build: ./stats_service
    command: celery -A stats_service worker --loglevel=info
    env_file:
      - stats_service/.env
    depends_on:
      - redis
      - stats_db
  

volumes:
  auth_data:
  tasks_data:
  stats_data: