

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    env_file:
      - auth_service/.env
    depends_on:
      - auth_db
      - redis

  tasks_service:
    build: ./tasks_service
    ports:
      - "8001:8001"
    env_file:
      - tasks_service/.env
    depends_on:
      - tasks_db


  auth_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=auth_db
    volumes:
      - auth_data:/var/lib/postgresql/data

  tasks_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tasks_db
    volumes:
      - tasks_data:/var/lib/postgresql/data


  redis:
    image: redis:6
    ports:
      - "6379:6379"

  auth_service_worker:
    build: ./auth_service
    command: celery -A auth_service worker --loglevel=info
    env_file:
      - auth_service/.env
    depends_on:
      - redis
      - auth_db


volumes:
  auth_data:
  tasks_data: