

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    env_file:
      - auth_service/.env
    depends_on:
      - auth_db
      - redis


  auth_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=auth_db
    volumes:
      - auth_data:/var/lib/postgresql/data


  redis:
    image: redis:6
    ports:
      - "6379:6379"


volumes:
  auth_data: