# Generated by Django 5.2 on 2025-04-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
