# Generated by Django 5.1.7 on 2025-05-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_auth', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
